### PR TITLE
PMM-6490 Overcome the limitation of 100 dbinstances

### PR DESCRIPTION
**Pull request by vlinevych**
`rds_exporter` crashes when there are more than 100 instances configured for enhanced monitoring.

RDS exporter calls cloudwatch's method `FilterLogEvents` with a parameter `LogStreamNames`,
which cannot be longer than 100 elements:
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html

This PR works it around by calling FilterLogEvents multiple times.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/rds_exporter?pullRequest=47) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/rds_exporter?pullRequest=47) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/rds_exporter?pullRequest=47) it.</sub>

**Comment by vlinevych** [comment]
CI is failing because of missing AWS credentials:
```
Error:      	AWS_ACCESS_KEY and AWS_SECRET_KEY environment variables must be set for this test
```

**Comment by vlinevych** [comment]
Hi @BupycHuk ,
is there something I can do in order to pass the CI?
It seems like aws credentials are not injected on purpose.

**Comment by vlinevych** [comment]
@AlekSi May I ask you to take a look at this, please?

**Comment by BupycHuk** [comment]
Hi @vlinevych! Thanks for the PR. Code looks good to me. We will test it and then merge if everything is ok.

**Comment by vlinevych** [comment]
@BupycHuk any news?

**Comment by BupycHuk** [comment]
@vlinevych sorry, but not yet. Our QAs a little bit busy with other tasks.
Have you already tested it?

**Comment by vlinevych** [comment]
@BupycHuk sure. I've built it from my fork and deployed onto my systems 2 months ago :)

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
