### PR TITLE
PMM-7724 Go mod

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-7724

### CODE REVIEW

**Comment by percona-csalguero** [comment]
@askomorokhov Could you check why tests are failing?

**Review by BupycHuk — APPROVED** [review]

**Review by BupycHuk — CHANGES_REQUESTED** [review]
please update go version to 1.16

**Review by percona-csalguero — DISMISSED** [review]
LGTM but please update Go to v1.16

**Review by percona-csalguero — APPROVED** [review]

**Comment by askomorokhov** [comment]
Done in https://github.com/percona/rds_exporter/pull/53

**Pull request closed without merging**
