### PR TITLE
Build the binary on Dockerfile itself

### PR DESCRIPTION
**Pull request by renan**
Allowing the image to be automatically built by DockerHub on push.

When accepted, please configure an automated build on DockerHub or a place where we can officially download from.

Works as intended in my own fork: https://hub.docker.com/repository/registry-1.docker.io/werkspot/rds_exporter/builds/6a4b5765-335f-4db5-9830-fe7a63b7a9a3

### CODE REVIEW

**Comment by renan** [comment]
The current build fails on Reviewdog with a 500 error. I can't retry it.

Is there anything else I can do?

Ping @BupycHuk @AlekSi

**Comment by denisok** [comment]
@renan could you please check #49 is that doin the same and better or not ?

**Comment by renan** [comment]
@denisok I did check. It is doing things differently and needs to explicitly set the origin repository as to the outdated version of Go modules (using gopkg) to work correctly. I believe this MR is better.

**Review by percona-csalguero — APPROVED** [review]

**Comment by askomorokhov** [comment]
Thank you for your PRs.
We have a general plan to automate releasing packages (including containers) of all exporters.
Added link to this PR as a reference to main Jira task.

**Pull request closed without merging**
