### PR TITLE
PMM-12339 remove go tip

### PR DESCRIPTION
**Pull request by atymchuk**
PMM-12339

https://goreleaser.com/deprecations/?h=rm+dist#-rm-dist

### CODE REVIEW

**Comment by atymchuk** [comment]
https://github.com/orgs/percona/teams/pmm-admins Could you please configure the github actions to run the tests?

**Review by JiriCtvrtka — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Comment by atymchuk** [comment]
The test failures are unrelated to this PR, tests have been failing since long. We need to fix them in a separate PR IMO.

**Comment by artemgavrilov** [comment]
@BupycHuk  please setup required rewiewers and set auto-merge (I can't find where to configure it)

**Comment by artemgavrilov** [comment]
@atymchuk I think it makes sense to change trigger from `on: [push, pull_request]` to `push on main` and  `pull_request` on everything else. (same as in other repos). Otherwise tests triggered twice in PRs.

**Comment by atymchuk** [comment]
> @atymchuk I think it makes sense to change trigger from `on: [push, pull_request]` to `push on main` and `pull_request` on everything else. (same as in other repos). Otherwise tests triggered twice in PRs.

I fixed this one, but the other one doesn't seem to suffer from the same problem.

Could you please remove the need to approve the workflow runs on every push? That seems to be too annoying.

Screenshot 2023-07-19 at 15 06 27

**Review by JiriCtvrtka — APPROVED** [review]

**Pull request merged**
