### PR TITLE
Enhanced monitoring: set cloudwatch query maxInterval=60 sec

### PR DESCRIPTION
**Pull request by vlinevych**
The motivation behind this PR is to reduce the number of requests to Cloudwatch, which are not cheap.
According to the current logic, refresh interval is set to the lowest value of `instance.EnhancedMonitoringInterval` found among the instances.

Although RDS [supports](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.Enabling.html) the granularity of `1, 5, 10, 15, 30, or 60`, the maxInterval is currently limited to 10 sec only.

In my case, most of my instances are configured for 60sec and 5 out of 6 requests to Cloudwatch return the same data.

I would like to reevaluate the decision that was made [back in 2018](https://github.com/percona/rds_exporter/pull/16/commits/c29dd75312e54fc0a6cd712cddaed19d285b6c45) 

Please let me know what do you think. 
Thanks.

### CODE REVIEW

**Review by JiriCtvrtka — APPROVED** [review]
For me it is fine. We have 60 seconds intervals also in another places.

@askomorokhov Do you agree?

**Review by askomorokhov — APPROVED** [review]

**Comment by vlinevych** [comment]
Thanks for the review!
CI is failing because of missing AWS credentials, there is not much I can do about it.

```Error:      	AWS_ACCESS_KEY and AWS_SECRET_KEY environment variables must be set for this test```

I kindly ask some of the collaborators to force-merge it.

**Comment by JiriCtvrtka** [comment]
@denisok Can you merge it? Because of waiting for lint.

**Comment by askomorokhov** [comment]
@vlinevych, thank you for your contribution! Merged https://github.com/percona/rds_exporter/pull/63

**Comment by Aleksa-del** [comment]
@vlinevych Hello! We would love to send you a gift from Percona for your contributions. Please, contact us at community-team@percona.com

**Pull request closed without merging**
